### ISSUE TITLE
Docker build on the dev environment failing with non availability of space.

### ISSUE THREAD

**Issue by Anand2bn** [medic/chis-visualizations#13]
Unable to perform docker build using following command under srv folder with below command.
/srv/airflow/docker-airflow$ sudo docker image build -t airflow-test .

below is the error.
dpkg: error: failed to write status database record about 'cpp-8' to '/var/lib/dpkg/status': No space left on device

Please let us know for any more information needed.

**Comment by ashish-medic** [comment]
Hi @medic/site-reliability-engineering can you please look into this.

**Comment by nomulex** [comment]
hi @ashish-medic / @Anand2bn  please share the instance url/ip in the ticket.

**Comment by Anand2bn** [comment]
Hi Team,

Thanks for the response. We have managed to free up the space by deleting the unused docker related files using docker system prune command and able to continue with building of docker images.

Thanks,
Anand | Accenture Data Lighthouse | Data & AI | Bangalore | Mobile: +91-9900864800
___________________________________________________________________________________
***@***.***D72574.89EAF5F0]
SEE THE DATA. WIELD THE DATA. WOW WITH DATA.

From: Alex Nyika Omuyonga ***@***.***>
Sent: Tuesday, March 30, 2021 2:44 PM
To: medic/chis-visualizations ***@***.***>
Cc: Narasimhamurth, Anand ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [medic/chis-visualizations] Docker build on the dev environment failing with non availability of space. (#13)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


hi @ashish-medic<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ashish-2Dmedic&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=laXa9vH8Dj6Ma8-y3aSWanwfaUj99D_EpfR1hsnFGaLMyHIpABEIkB4vNGVP8A0x&m=PMjjRv2_38uRlnAkoQ3st-7RP33OYHU7NBkOfFg25-Y&s=4_qkr4c7rKgBN9zXKYO7-bpUlXlO5mFd0Bnh-hXmlZs&e=> / @Anand2bn<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Anand2bn&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=laXa9vH8Dj6Ma8-y3aSWanwfaUj99D_EpfR1hsnFGaLMyHIpABEIkB4vNGVP8A0x&m=PMjjRv2_38uRlnAkoQ3st-7RP33OYHU7NBkOfFg25-Y&s=0tE0Lg8TRY71gpIspfUz5To7jYynni_AmEYTsxK5Qko&e=> please share the instance url/ip in the ticket.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_medic_chis-2Dvisualizations_issues_13-23issuecomment-2D810057489&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=laXa9vH8Dj6Ma8-y3aSWanwfaUj99D_EpfR1hsnFGaLMyHIpABEIkB4vNGVP8A0x&m=PMjjRv2_38uRlnAkoQ3st-7RP33OYHU7NBkOfFg25-Y&s=jNn4Zj11IRAgt4_w8K13d9JJdKlHW8rKVvIJqNPb8r0&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AS6V4CTYQI2XIGRXSEGZIB3TGGI5XANCNFSM42BMZKWA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=laXa9vH8Dj6Ma8-y3aSWanwfaUj99D_EpfR1hsnFGaLMyHIpABEIkB4vNGVP8A0x&m=PMjjRv2_38uRlnAkoQ3st-7RP33OYHU7NBkOfFg25-Y&s=d0Nas7cTO8X1lUEud_uH-ylBk8X4CsrtNLVhd4k43n8&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com
