### ISSUE TITLE
Infrastructure for Community of Practice (CoP) Interoperability Project

### ISSUE THREAD

**Issue by michaelkohn** [medic/chis-visualizations#2]
[Original issue ](https://github.com/medic/medic-infrastructure/issues/265) in private Medic repo, moving the convo here to make it easier to triage.

- [x] Set up empty Ubuntu server 
- [x] Obtain ssh keys from users
- [x] Install ssh keys for users
- [x] Confirm connectivity successful
- [x] Determine ports to open
- [x] Open ports

**Comment by nomulex** [comment]
I granted access to those ports. @nsikak-e-akpakpan , do you have any other ports you want opened?

**Comment by nomulex** [comment]
Here are the ports that are currently open.

**Comment by nomulex** [comment]
Here are the ports that are currently open.
![image](https://user-images.githubusercontent.com/3070004/110761114-694c2000-8260-11eb-8458-8ab5209b0d94.png)

**Comment by mrjones-plip** [comment]
@medic/site-reliability-engineering - I'm jumping in to help @nsikak-e-akpakpan & @f-odhiambo .  Can you please grant me SSH access ([keys here](https://github.com/mrjones-plip.keys)) with sudo to the `cop.app` instance when you get a sec? 

Much thanks!

**Comment by nomulex** [comment]
access granted and password shared on 1password

**Comment by mrjones-plip** [comment]
> access granted and password shared on 1password

Much thanks @nomulex  - I tested the credentials earlier and it all works!

**Comment by nsikak-e-akpakpan** [comment]
@f-odhiambo Can you provide your ssh key to Alex to add on the CoP server.  @nomulex please kindly add @f-odhiambo to the CoP Server so we can complete the setup work.  Thanks.

**Comment by f-odhiambo** [comment]
Hey @nomulex Kindly add the ssh key attached 
[sshkey.txt](https://github.com/medic/chis-visualizations/files/6156642/sshkey.txt)

**Comment by nomulex** [comment]
Credentials shared  privately with @f-odhiambo  on digital square slack

**Comment by f-odhiambo** [comment]
I have lost access  - ssh: connect to host cop.app.medicmobile.org port 33696: Operation timed out

**Comment by mrjones-plip** [comment]
@f-odhiambo  - I see the same thing!  Tracking this in a [separate issue](https://github.com/medic/chis-visualizations/issues/5) and reaching out to SRE in Medic Slack channel.

**Comment by nomulex** [comment]
Access has been enabled again.

**Comment by mrjones-plip** [comment]
From @nsikak-e-akpakpan:

- [ ] @f-odhiambo, please let's proceed with re-running the installation script again just in case you run into the problem from #5  again.  
- [ ] Also note the feedback from @Hareet on the ticket to make sure that use the right directories for the installation ([Change docker configuration](https://medium.com/developer-space/how-to-change-docker-data-folder-configuration-33d372669056), [Move docker's default to another directory](https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux) to the extent possible. 
- [ ] If the issue happens again, we should log a ticket with Instant-OpenHIE to get input.  
- [ ] We want to run through the setup end to end without error (warnings ok) 
- [ ] Once we have the setup up and running, we should do a tech walkthrough 
- [ ] Before we @mrjones-plip closes the ticket.

**Comment by mrjones-plip** [comment]
Per chat w/ @nsikak-e-akpakpan  - closing this and opening other tickets to track outstanding to do items.

Thanks again @nomulex  & @Hareet  for all your help with this!
