### ISSUE TITLE
cop.app.medicmobile.org is inaccessible

### ISSUE THREAD

**Issue by mrjones-plip** [medic/chis-visualizations#5]
The instance created in #2 `cop.app.medicmobile.org`,  appears to be inaccessible.  We were not expecting this and hope to continue work on it. 

Thanks!

```
 ping 52.56.228.185
PING 52.56.228.185 (52.56.228.185) 56(84) bytes of data.
^C
--- 52.56.228.185 ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9196ms
```

```
ssh -vvv cop.app.medicmobile.org -p 33696
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /home/mrjones/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolving "cop.app.medicmobile.org" port 33696
debug2: ssh_connect_direct
debug1: Connecting to cop.app.medicmobile.org [52.56.228.185] port 33696.
debug1: connect to address 52.56.228.185 port 33696: Connection timed out
ssh: connect to host cop.app.medicmobile.org port 33696: Connection timed out
```

**Comment by nsikak-e-akpakpan** [comment]
Me too.  Can someone reboot from EC2 console?

**Comment by mrjones-plip** [comment]
@Hareet  (SRE) has reported:

> I’ll look at it shortly

Thanks!

**Comment by Hareet** [comment]
Rebooting ec2 still fails. 

Do you know the amount of resources you require for what is being installed? I will try to create an image of the existing server and move it to a new one.

**Comment by nsikak-e-akpakpan** [comment]
I would recommend c4.4xlarge or higher with 32GB of storage
![image](https://user-images.githubusercontent.com/75056490/111656090-3530ac00-87d8-11eb-9016-30777906d7a4.png)

**Comment by Hareet** [comment]
@nsikak-e-akpakpan

It seems as if people are installing and saving their data directly on the root disk. There was a 100gb extra hard disk on the server that was meant for data and all applications, but it is hardly being used. The root disk is completely full, and causing the ssh daemon to be unable to start. 

It's more difficult to increase the size on the root disk than the other volume once it reaches capacity. We will have this server back up for you by tomorrow, but please ensure on-going work gets installed and saved to the correct volume.

**Comment by nsikak-e-akpakpan** [comment]
> @nsikak-e-akpakpan
> 
> It seems as if people are installing and saving their data directly on the root disk. There was a 100gb extra hard disk on the server that was meant for data and all applications, but it is hardly being used. The root disk is completely full, and causing the ssh daemon to be unable to start.
> 
> It's more difficult to increase the size on the root disk than the other volume once it reaches capacity. We will have this server back up for you by tomorrow, but please ensure on-going work gets installed and saved to the correct volume.

Thanks, @Hareet.  The setup scripts give us very limited flexibility with file location.  It might be necessary to beef up the root disk so we can get through the initial setup and then determine whether we want to take the step of editing the setup script to distribute files to data and application mount points.  Thanks for the help.

**Comment by Hareet** [comment]
@nsikak-e-akpakpan 👍 

The root disk is now 50gb, but we are still having issues booting the larger root disk. Hoping something didn't get corrupted beyond repair.

 @nomulex will continue investigating on Friday.

**Comment by nomulex** [comment]
So,  I have managed to make the instance accessible again. The issue was due to firewall rules added yesterday by @f-odhiambo  during one of the installations. I go to know this by mounting the root device to an accessible instance and reading journalctl logs. 
Output from logs
```bash
root@ip-10-35-4-161:/srv/mnt# journalctl --directory=/srv/var/log/journal/ -u ufw
-- Logs begin at Tue 2021-02-16 12:57:47 UTC, end at Fri 2021-03-19 08:46:22 UTC. --
Mar 18 14:56:43 ip-10-35-4-237 systemd[1]: Started Uncomplicated firewall.
-- Reboot --
Mar 18 15:00:19 ip-10-35-4-237 systemd[1]: Started Uncomplicated firewall.
-- Reboot --
Mar 18 15:06:17 ip-10-35-4-237 systemd[1]: Started Uncomplicated firewall.
-- Reboot --
Mar 18 15:26:13 ip-10-35-4-237 systemd[1]: Started Uncomplicated firewall.
```
Output from @f-odhiambo's bash history

``bash
root@ip-10-35-4-161:/srv/home/odhiambo# cat .bash_history 
ls
lsb_release -a
sudo apt update
sudo apt install apache2
sudo ufw app list
sudo ufw allow 'Apache'
sudo ufw status
sudo ufw allow 'Apache'
sudo systemctl status apache2
sudo systemctl restart apache2
sudo ufw app list
sudo ufw status
sudo ufw enable
sudo iptables -L
sudo ufw enable
sudo ufw status 
if config
ifconfig

```

The starting of the ufw service was consistent with the time when all access to the VM was lost yesterday.  So I went ahead to disable ufw through a startup script. This then granted access back to the box.  Kindly check the firewall rules you would like to have on the box before you enable ufw again. 
If all is well please close this ticket.

**Comment by f-odhiambo** [comment]
@nomulex Thank you for your assistance and will be more prudent next time. Kindly add for me this ssh key as well 
[mp-air-key.txt](https://github.com/medic/chis-visualizations/files/6170997/mp-air-key.txt)

**Comment by nomulex** [comment]
Done

**Comment by nsikak-e-akpakpan** [comment]
@nomulex Thank you so much for helping address the issue and the excellent diagnosis.  

- [ ] @f-odhiambo, please let's proceed with re-running the installation script again just in case you run into the problem again.  

- [ ] Also note the feedback from @Hareet on the ticket to make sure that use the right directories for the installation ([Change docker configuration](https://medium.com/developer-space/how-to-change-docker-data-folder-configuration-33d372669056), [Move docker's default to another directory](https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux) to the extent possible. 

- [ ] If the issue happens again, we should log a ticket with Instant-OpenHIE to get input.  

- [ ] We want to run through the setup end to end without error (warnings ok) 

- [ ] Once we have the setup up and running, we should do a tech walkthrough 

- [ ] Before we @mrjones-plip closes the ticket.

**Comment by mrjones-plip** [comment]
Thanks so much @nomulex ! Nice work there.

@nsikak-e-akpakpan - moved your comments to the [primary install](#2 ) ticket so this "server is down" ticket can be close.
