### ISSUE TITLE
Need more ports opened

### ISSUE THREAD

**Issue by nsikak-e-akpakpan** [medic/chis-visualizations#6]
@nomulex, Additional ports to Open for Dev Environment testing.  Ports are set by the installation script and it takes too much effort to modify the scripts to use other port numbers.  
- HAPI FHIR: 3447 (priority), 8088, 8089. Click here to verify access to [HAPI FHIR](http://cop.app.medicmobile.org:3447)
- Instantohie-mscd-mock service: 4000
- openhim mapping mediator:  3003
- Redis: 6379
- Kibana: 5601
- Postgres 5432, 5442, 5452
- Open Register: 3004
- Elastic Search API: 9200
- MongoDB Ports: 27017, 27018, 27019
- MySQL: 3306
- Openhim core: 5000, 5001, 5002, 5003, 5004, 5005

**Comment by nomulex** [comment]
These have been unblocked.   I hope though that this is a test box. The number of applications being installed on just one box creates a recipe for disaster.  In addition, these services having open ports that are world accessible makes it a bit too open, generally, these services should talk to each other through a vpc.   ^^ @michaelkohn @henokgetachew @Hareet

**Comment by nsikak-e-akpakpan** [comment]
> These have been unblocked. I hope though that this is a test box. The number of applications being installed on just one box creates a recipe for disaster. In addition, these services having open ports that are world accessible makes it a bit too open, generally, these services should talk to each other through a vpc. ^^ @michaelkohn @henokgetachew @Hareet

Thanks, @nomulex.  Yes, this is a Dev Sandbox to configure and refine OpenHIE-FHIR interoperability.  Once we get all the services working as they should, we hope to devote time to distributing the services to different instances and enabling their interaction via vpc.    For now, let's secure access by limiting to IP addresses of the team members that will be doing the interoperability DevOps work.
